name: kotlin-actor-sample

services:
  seed:
    container_name: pekko-cluster-seed
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: node1
    ports:
      - "2551:2551"
    environment:
      CLUSTER_PORT: 2551
      CLUSTER_IP: seed
  c1:
    container_name: pekko-cluster-c1
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: node2
    ports:
      - "2552:2552"
    environment:
      CLUSTER_PORT: 2552
      CLUSTER_IP: c1
  c2:
    container_name: pekko-cluster-c2
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: node3
    ports:
      - "2553:2553"
    environment:
      CLUSTER_PORT: 2553
      CLUSTER_IP: c2
