name: kotlin-actor-sample

services:
  node-1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "2551:2551"
    volumes:
      - ../apps/.gradle:/home/gradle/.gradle
      - ../apps:/workspace
    environment:
      - GRADLE_USER_HOME=/home/gradle/.gradle
    command: ["gradle", "run"]

  node-2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "2552:2552"
    volumes:
      - ../apps/.gradle:/home/gradle/.gradle
      - ../apps:/workspace
    environment:
      - GRADLE_USER_HOME=/home/gradle/.gradle
    command: ["gradle", "run"]
    depends_on:
      - node-1 